name: Setup Node.js environment and cache npm dependencies
description: Checkout code-> setup node.js env -> cache its dependencies -> point package.json file
on:
  workflow_dispatch:

jobs:
  setupNodeJsEnvAndCacheNpmDependencies:
    name: Setup Node.js environment and cache npm dependencies
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v7

      - name: setup node js env and cache its npm dependencies
        run: | 
              echo "current directory before cache restore -> $pwd"
              ls -ltrh
              
      - uses: actions/setup-node@v7
        name: caching npm dependencies
        id: restoreNpmCache
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: demojs/package-lock.json

      - run: |
              cd demojs/
              npm ci
              node demo.js

      - name: check if cache is restored
        if: steps.restoreNpmCache.outputs.cache-hit == 'true'
        run: |
              echo "cache restored !!"
              ls -ltrh demojs/node_modules
        
          
