name: Setup Node.js environment and cache npm dependencies
description: Checkout code-> setup node.js env -> cache its dependencies -> point package.json file
on:
  workflow_dispatch:

jobs:
  setupNodeJsEnvAndCacheNpmDependencies:
    name: Setup Node.js environment and cache npm dependencies
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v7

      - name: setup node js env and cache its npm dependencies
        run: | 
              pwd
              ls -ltrh
              
      - uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: ./demoJsProject/package-lock.json
        
          
