name: Try out the parameterized job feature using workflow_dispacth inputs and matrix job too

on:
  workflow_dispatch:
    inputs:
      env:
        description: test env
        required: true
        type: choice
        options:
          - QA1
          - QA2
        default: QA1

jobs:
  acceptInputFromWfw:
    environment: ${{ github.event.inputs.env }}
    runs-on: ubuntu-latest
    steps:
      - name: echo the input
        run: |
              echo ${{ github.event.inputs.env}}
  matrixJob:
    strategy:
      matrix:
        foo: [bar1, bar2]
        foo2: [bar3, bar4] 
    runs-on: ubuntu-latest
    steps:
      - name: matrix job ${{ matrix.foo }} - ${{ matrix.foo2 }}
        run: |
              echo ${{ matrix.foo }}
              echo ${{ matrix.foo2 }}
